#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

vmware-user &
vmware-user-suid-wrapper &
wmname LG3D &
picom --config $HOME/.config/picom/picom.conf &

# Load wallpaper
feh --bg-fill $HOME/.config/Wallpapers/wall.png &

# Edit with the theme you want
~/.config/polybar/launch.sh --hack &
